### PR TITLE
[udisks2] Ability to rename SD card and partitions. JB#54905

### PR DESCRIPTION
**Pull request by amakarik**

### CODE REVIEW

**Review by Thaodan — CHANGES_REQUESTED** [review]
No need to mention SD cards.
The commit message says the ability to rename partitions however its about renaming those without admin permissions.

I think we should also look if we should let not all users do it but just the main user.

**Comment by amakarik** [comment]
> No need to mention SD cards. The commit message says the ability to rename partitions however its about renaming those without admin permissions.
> 
> I think we should also look if we should let not all users do it but just the main user.

Ok, I can explain. The main idea is to show "Rename" menu item in the context menu for partition in the Files application. Files application is used by regular user so we need to add permissions to the regular user.

**Comment by pvuorela** [comment]
I'm a little hesitant if the current user should have access to these without any questions asked. Hmh.

**Comment by pvuorela** [comment]
And the version update in pr 3 seems to be proceeding, at least that could be nice to get in as first thing.

**Comment by amakarik** [comment]
> I'm a little hesitant if the current user should have access to these without any questions asked. Hmh.

Without such permissions regular application will not be able to rename partition (Files and etc)

**Comment by pvuorela** [comment]
> Without such permissions regular application will not be able to rename partition (Files and etc)

That's the reason why I'm hesitant. Mounts and label renames are somewhat privileged operations.

How about the settings app, didn't yet try but did that now require policy changes? The first target could be having that working.

**Comment by amakarik** [comment]
> > Without such permissions regular application will not be able to rename partition (Files and etc)
> 
> That's the reason why I'm hesitant. Mounts and label renames are somewhat privileged operations.
> 
> How about the settings app, didn't yet try but did that now require policy changes? The first target could be having that working.

Settings app doesn't require policy changes. It's working with current policy

**Comment by pvuorela** [comment]
Discussed with @okodron and @rainemak that we could for now just have the settings app side and close this one. Can revisit later if we want to have some way to provide specific apps ability to rename. Or maybe have some system confirmation dialog.

**Pull request closed without merging**
